version: "3.8"
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    build:
      context: ./
      dockerfile: ./dockerfile_web
    container_name: gf-vue-admin-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    build:
      context: ./
      dockerfile: ./dockerfile_server
    container_name: gf-vue-admin-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.21
    container_name: gf-vue-admin-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'gf-vue-admin' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: "gdkid,,.." # root管理员用户密码
    volumes:
      - '.docker-compose/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      network:
        ipv4_address: 177.7.0.13
  redis:
    image: redis:6.0.6
    container_name: gf-vue-admin-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      network:
        ipv4_address: 177.7.0.14